#!/bin/sh
alias install='sudo apt-get install'
alias la='ls -alh'
cs() { cd "$1" && ls -alh; }
dbexec() {ssh -t fahassan.souq@fahassan.souq.jdc.dev "mysql -h devmarkdb20151016.ciht5im6msyg.eu-west-1.rds.amazonaws.com -u souq -puHhFHUQP souq_hitmeister -e '$1'" }
alias downloads='cs ~/Downloads'
alias my='ssh slimfadi@slimfadi.webfactional.com'
alias add_alias='vim ~/bin/dotfiles/zsh/aliases'
alias o='open'
alias commit_files='git diff-tree --no-commit-id --name-only -r'
alias push='git push -f dev HEAD:master'
alias fetch='git fetch origin'





alias db='ssh -t fahassan.souq@fahassan.souq.jdc.dev '\''mysql -h devmarkdb20151016.ciht5im6msyg.eu-west-1.rds.amazonaws.com -u souq -puHhFHUQP souq_hitmeister'\'

alias dbe='ssh -t fahassan.souq@fahassan.souq.jdc.dev '\''mysql -h devpredb.ciht5im6msyg.eu-west-1.rds.amazonaws.com -u souq -puHhFHUQP -e "show databases;"'\'

alias ggraph='git log --graph --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset" --abbrev-commit --date=relative'

alias undo_pull='git reset HEAD@{1}'

alias editgit="subl `git status --porcelain | awk '{print $2}'`"

alias sync_music='rsync -avz -e ssh --exclude=.DS_Store --delete ~/Dropbox/music/ osmc@192.168.1.3:~/Music/'
alias sync_music_local='sudo rsync -avz -e ssh --exclude=.DS_Store --delete ~/Dropbox/music/ /var/www/music/music/ && sudo chmod -R 777 /var/www/music/music'
alias subl='/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl'

alias chrome='/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome &'

ma() {mv ~/Dropbox/music/$1 ~/Dropbox/music\ archive/$1 }
