#!/bin/sh
alias install='sudo apt-get install'
alias cp='cp -iv'
alias mv='mv -iv'
alias la='ls -alh'
cs() { cd "$1" && ls --sort time -alh; }
alias documents='cs ~/Documents'
alias downloads='cs ~/Downloads'
alias desktop='cs ~/Desktop'
alias music='cs ~/dumpfile/temp_music'
alias videos='cs ~/Videos'
alias books='cs ~/dumpfile/books'
alias learning='cs ~/dumpfile/learning'
alias dumpfile='cs ~/dumpfile'
alias movies='cs ~/dumpfile/movies '
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias go='google-chrome http://facebook.com http://gmail.com http://email.slimfadi.com http://music.fadi-webs.com http://tickets.fadi-webs.com'
alias my='ssh slimfadi@slimfadi.webfactional.com'
alias www='cs /var/www'
alias sph='cs /usr/local/sphinx/'
alias add_alias='vim ~/bin/dotfiles/zsh/aliases'
alias o='xdg-open'
alias projects='cs ~/Desktop/projects'
alias muzul='cs ~/Desktop/projects/muzul/'


#opensooq stuff
alias os_web1='ssh -i ~/.ssh/dev_web01-1.pem ubuntu@ec2-54-224-50-199.compute-1.amazonaws.com'
alias os_admin='ssh -i ~/.ssh/dev_web02.pem ubuntu@ec2-54-242-210-252.compute-1.amazonaws.com'
alias os_db1='ssh -i ~/.ssh/dev_db01.pem ubuntu@54.225.65.80'
alias os_solr='ssh -i ~/.ssh/solr_dev.pem ubuntu@54.225.65.95'
alias apache_log='tail -f /var/log/apache2/error.log'
alias ares='sudo service apache2 restart'
alias sites_available='sudo subl /etc/apache2/sites-available/default'
alias dev_log='tail -f /var/www/dev_2.8.1/protected/runtime/application.log'
alias test_log='tail -f /var/www/opensooq/protected/runtime/application.log'
alias checklists='cd ~/Desktop/checklists'
alias svndiff='svn diff --diff-cmd /usr/bin/diff -x "-w"'
alias solr_dev='cd /var/www/dev_2.8/solr-4.3.0/solr/;java -Xms512M -Xmx1024M -jar start.jar'
alias solr_test='cd /var/www/opensooq/solr-4.3.0/solr/;java -Xms512M -Xmx1024M -jar start.jar'
function new_check_list() { cp ~/Desktop/checklists/template.txt ~/Desktop/checklists/$1.txt; cd ~/Desktop/checklists; subl $1.txt;  }
alias chmod='sudo chmod'
alias os_start='subl &; tmuxinator start os_dev'
alias os='cd /var/www/opensooq'
alias ggraph='git log --graph --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset" --abbrev-commit --date=relative'
colors() {
	for i in {0..255} ; do
		printf "\x1b[38;5;${i}mcolour${i}\n"
	done
}
solr() {
	cd /var/www/solr/solr-4.6.0/solr/;
	java -jar start.jar;
}
ass() {
	cd /var/www/opensooq/httpdocs/assets
	sudo rm -r *
}


function extract() {
	if [ -f $1 ] ; then
		case $1 in
			*.tar.bz2) tar xvjf $1 ;;
			*.tar.gz) tar xvzf $1 ;;
			*.bz2) bunzip2 $1 ;;
			*.rar) unrar x $1 ;;
			*.gz) gunzip $1 ;;
			*.tar) tar xvf $1 ;;
			*.tbz2) tar xvjf $1 ;;
			*.tgz) tar xvzf $1 ;;
			*.zip) unzip $1 ;;
			*.Z) uncompress $1 ;;
			*.7z) 7z x $1 ;;
			*) echo "'$1' cannot be extracted via >extract<" ;;
		esac
	else
		echo "'$1' is not a valid file!"
	fi
}
